//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinalPAP
{


    public partial class admin
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView GridViewUsers;
        protected global::System.Web.UI.WebControls.GridView GridViewReports;
        protected global::System.Web.UI.WebControls.GridView GridViewUserVideos;
        protected global::System.Web.UI.WebControls.Panel PanelUserVideos;
        protected global::System.Web.UI.WebControls.GridView GridViewVideoUsers;
        protected global::System.Web.UI.WebControls.Label SelectedUsernameLabel;

    }
}
