//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinalPAP
{
    public partial class editar_video
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// videoThumbnail control (image preview).
        /// </summary>
        /// <remarks>
        /// Used to display the current thumbnail image.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload videoThumbnail;

        /// <summary>
        /// thumbnailUpload control (FileUpload for new thumbnail).
        /// </summary>
        /// <remarks>
        /// Allows uploading a new thumbnail.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload thumbnailUpload;

        /// <summary>
        /// videoTitle control.
        /// </summary>
        /// <remarks>
        /// Input field for the video title.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox videoTitle;

        /// <summary>
        /// videoDescription control.
        /// </summary>
        /// <remarks>
        /// Input field for the video description.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox videoDescription;

        /// <summary>
        /// visibility control.
        /// </summary>
        /// <remarks>
        /// Dropdown to select video visibility (public/private).
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList visibility;

        /// <summary>
        /// btnSaveChanges control.
        /// </summary>
        /// <remarks>
        /// Button to save changes to the video.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSaveChanges;

        /// <summary>
        /// btnDeleteVideo control.
        /// </summary>
        /// <remarks>
        /// Button to delete the video.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDeleteVideo;

        protected global::System.Web.UI.WebControls.DropDownList videoCategory;


    }
}
