//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinalPAP
{
    public partial class upload
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox videoTitle;
        protected global::System.Web.UI.WebControls.TextBox videoDescription;
        protected global::System.Web.UI.WebControls.DropDownList visibility;
        protected global::System.Web.UI.WebControls.FileUpload videoFile;
        protected global::System.Web.UI.WebControls.FileUpload videoThumbnail;
        protected global::System.Web.UI.WebControls.DropDownList videoCategory;



    }
}

